#!/bin/bash

setup_ssh()
{
    if [ ! -e /var/lib/maculaos/ssh ]; then
        mkdir -p /var/lib/maculaos
        cp -rf /etc/ssh /var/lib/maculaos/ssh
    fi
    rm -rf /etc/ssh
    ln -s /var/lib/maculaos/ssh /etc/ssh
}

setup_rancher_node()
{
    mkdir -p /etc/rancher
    mkdir -p /var/lib/maculaos/node
    ln -s /var/lib/maculaos/node /etc/rancher/
}

setup_ssh
setup_rancher_node
