#!/bin/bash

source $SCRIPTS/functions

for x in $(cat /proc/cmdline); do
    case $x in
        rescue)
            MODE=shell
            ;;
        macula.mode=*)
            MODE=${x#macula.mode=}
            ;;
        macula.fallback_mode=*)
            FALLBACK_MODE=${x#macula.fallback_mode=}
            ;;
    esac
done

MODE_WAIT_SECONDS=30

while [ -z "$MODE" ] && (( MODE_WAIT_SECONDS > 0 )); do

if [ -z "$MODE" ] && [ -n "$(blkid -L K3OS_STATE)" ]; then
    MODE=disk
fi

if [ -n "$MACULA_MODE" ]; then
    MODE=$MACULA_MODE
fi

if [ -z "$MODE" ]; then
    MODE="${FALLBACK_MODE}"
fi

if [ -z "$MODE" ] && [ "$(stat -f -c '%T' /)" != "tmpfs" ]; then
    MODE=local
fi

if [ -z "$MODE" ]; then
  echo "Couldn't determine boot mode, waiting $MODE_WAIT_SECONDS seconds..."
  sleep 1
  MODE_WAIT_SECONDS=$((MODE_WAIT_SECONDS - 1))
fi
done

if [ -z "$MODE" ]; then
    pfatal "Failed to determine boot mode (did you forget to set macula.mode?)"
elif [ ! -e $SCRIPTS/mode-${MODE} ]; then
    pfatal "Mode script does not exist for ${MODE}"
else
    echo "$MODE" > /run/macula/mode
fi
