#!/bin/bash

TARGET=/run/macula/target

source /usr/lib/os-release

grow()
{
    parted $1 resizepart $2 100%
    partprobe $1
    sleep 2
    e2fsck -f $3
    resize2fs $3
}

setup_mounts()
{
    mkdir -p $TARGET
    mount -L MACULAOS_STATE $TARGET

    if [ -e $TARGET/macula/system/growpart ]; then
        read DEV NUM < $TARGET/macula/system/growpart
        if [ ! -e "${DEV}${NUM}" ]; then
            # /dev/sda2 => /dev/sda2
            # /dev/nvme0n1p2 => /dev/nvme0n1p2
            PART=$(blkid -L MACULAOS_STATE)

            # /dev/sda2 => /dev/sda
            # /dev/nvme0n1p2 => /dev/nvme0n1
            DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

            # /dev/sda2 => 2
            # /dev/nvme0n1p2 => 2
            NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
        fi
        if [ -e "${PART:=${DEV}${NUM}}" ]; then
            umount $TARGET
            grow $DEV $NUM $PART || true
            mount -L MACULAOS_STATE $TARGET
        fi
        rm -f $TARGET/macula/system/growpart
    fi
}

setup_kernel_squashfs()
{
    KER_SRC="/.base/macula/system/kernel/$(uname -r)/kernel.squashfs"
    KER_DEST="$TARGET/macula/system/kernel/$(uname -r)/kernel.squashfs"
    if [ -e $KER_SRC ] && [ ! -e $KER_DEST ]; then
        mkdir -p $(dirname ${KER_DEST})
        cp -r $KER_SRC $KER_DEST
    fi
}

setup_macula()
{
    if [ -e $TARGET/macula/system/macula/current/maculaos ]; then
        return 0
    fi

    MACULA_SRC=/.base/macula/system/macula/current/maculaos
    MACULA_FILE=$TARGET/macula/system/macula/${VERSION_ID}/maculaos

    if [ ! -e ${MACULA_SRC} ]; then
        return 0
    fi

    if [ ! -e ${MACULA_FILE} ]; then
        mkdir -p $(dirname ${MACULA_FILE}.tmp)
        cp -f ${MACULA_SRC} ${MACULA_FILE}.tmp
        mv -f ${MACULA_FILE}.tmp ${MACULA_FILE}
    fi

    ln -sf ${VERSION_ID} $TARGET/macula/system/macula/current
}

setup_init()
{
    if [ -e $TARGET/sbin/init ]; then
        return 0
    fi

    mkdir -p $TARGET/sbin
    ln -sf ../macula/system/macula/current/maculaos $TARGET/sbin/init
}

setup_k3s()
{
    if [ -e $TARGET/macula/system/k3s/current/k3s ]; then
        return 0
    fi

    for i in $(ls -drt $TARGET/macula/system/k3s/*); do
        if [ ! -L "$i" ]; then
            LATEST=$i
            break
        fi
    done

    if [ -e "${LATEST}" ]; then
        ln -sf $(basename "${LATEST}") $TARGET/macula/system/k3s/current
        return 0
    fi
}

takeover()
{
    if [ ! -e macula/system/takeover ]; then
        return 0
    fi

    touch macula/system/factory-reset

    if [ -L sbin ]; then
      rm -f sbin
    fi

    for i in *; do
        case $i in
            boot|macula|sbin)
                ;;
            *)
                rm -rf $i
        esac
    done
    for i in sbin/*; do
        case $i in
            sbin/init|sbin/k3s|sbin/maculaos)
                ;;
            *)
                rm -rf "$i"
        esac
    done

    rm -rf boot/[^g]*
    rm -f macula/system/takeover
    rm -rf macula/data
    sync
    
    if [ -e macula/system/poweroff ]; then
        rm -f macula/system/poweroff
        sync
        poweroff -f
    else
        reboot -f
    fi
}

setup_mounts
setup_macula
setup_kernel_squashfs
setup_init
setup_k3s

cd $TARGET

takeover || true

if [ -e macula/system/factory-reset ] || [ -e macula/system/ephemeral ]; then
    rm -rf macula/data macula/system/factory-reset
fi

losetup -d /dev/loop0 || true
mount --make-rprivate /
mkdir -p .root
pivot_root . .root
MACULA_MODE=local exec /sbin/init
