#!/bin/bash

set -e

if [ $(whoami) != "root" ]
then
	echo "This script must be run as root."
	exit 1
fi

PROC=$(uname -m)

# Take a parameter of the version number (i.e. v0.4.0) if it is given, otherwise use latest
if [ -z $MACULA_VERSION ]
then
	MACULA_VERSION=$(curl -sL api.github.com/repos/macula-io/macula-os/releases/latest | jq .tag_name -r)
fi

if [ $PROC == "x86_64" ]
then
	ARCH="amd64"
elif [ $PROC == "aarch64" ]
then
	ARCH="arm64"
elif [[ $PROC == arm* ]] # catches armv7l and armhf
then
	ARCH="arm"
else
	echo "Unsupported CPU architecture."
	exit 1
fi

echo "Upgrading MaculaOS to ${MACULA_VERSION}"

cd /macula/system
mount -o remount,rw .
curl -fsSL "https://github.com/macula-io/macula-os/releases/download/${MACULA_VERSION}/macula-rootfs-${ARCH}.tar.gz" | tar xz --strip-components=3
sync

echo "Upgrade complete! Please reboot."
