#!/bin/bash
set -e

rescue() {
    echo ERROR "Something went wrong, run with cmdline macula.debug for more logging"
    echo Dropping to shell
    exec bash
}

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

. /usr/libexec/macula/functions
. /usr/lib/os-release

pinfo Welcome to $PRETTY_NAME

if [ "$MACULA_DEBUG" = "true" ]; then
    set -x
fi

if ! ${SCRIPTS}/bootstrap; then
    rescue
fi

exec >/dev/console </dev/console 2>&1

reinit_debug

if ! ${SCRIPTS}/mode; then
    rescue
fi

trap rescue EXIT

export MACULA_MODE=$(</run/macula/mode)
pinfo Running mode: ${MACULA_MODE}
source $SCRIPTS/mode-${MACULA_MODE}

pinfo Booting system
source $SCRIPTS/boot

exec /sbin/init
