#!/bin/sh
# Generate /etc/issue with MaculaOS banner

. /etc/os-release

ESC=$(printf '\033')
C="${ESC}[1;36m"
O="${ESC}[1;33m"
W="${ESC}[1;37m"
G="${ESC}[0;37m"
R="${ESC}[0m"

cat > /etc/issue << BANNER

${C}    o-------o${R}
${C}   /|       |\\${R}       ${O}+========================+${R}
${C}  o-+--o----+-o${R}     ${O}||${R}${W}      Macula OS       ${R}${O}||${R}
${C}   \\|\\ | /| /${R}       ${O}+========================+${R}
${C}    o--O--o${R}
${C}   /|  |  |\\${R}        ${W}Decentralized Edge Computing Platform${R}
${C}  o----o----o${R}

${G}  $PRETTY_NAME - Kernel \r on \m (\l)${R}

BANNER

NICS=$(ip -br addr show 2>/dev/null | grep -E -v '^(lo|flannel|cni|veth|docker|br-)' | head -3)
if [ -n "$NICS" ]; then
    printf '%s  Network:%s\n' "$C" "$R" >> /etc/issue
    printf '%s%s%s\n\n' "$G" "$NICS" "$R" >> /etc/issue
fi

printf '%s  Login: %smacula%s / %smacula%s\n\n' "$W" "$O" "$W" "$O" "$R" >> /etc/issue
