#!/bin/bash
# Generate /etc/issue with colorful MaculaOS banner

. /etc/os-release

# ANSI color codes (use $'...' for escape sequences)
O=$'\033[1;33m'    # Bold yellow (closest to orange #FD4F00)
C=$'\033[1;36m'    # Cyan
W=$'\033[1;37m'    # White
G=$'\033[0;37m'    # Gray
R=$'\033[0m'       # Reset

# Generate colorful banner
cat > /etc/issue << BANNER
${O}
      .o---o.       ${W}__  __                 _        ___  ____${R}
${O}     /|     |\\     ${W}|  \\/  | __ _  ___ _   _| | __ _ / _ \\/ ___|${R}
${O}    o-+-----+-o    ${W}| |\\/| |/ _\` |/ __| | | | |/ _\` | | | \\___ \\${R}
${O}     \\|     |/     ${W}| |  | | (_| | (__| |_| | | (_| | |_| |___) |${R}
${O}      'o---o'      ${W}|_|  |_|\\__,_|\\___|\\__,_|_|\\__,_|\\___/|____/${R}
${O}        \\ /${R}
${O}         o         ${C}Decentralized Edge Computing Platform${R}

${G}  $PRETTY_NAME - Kernel \r on \m (\l)${R}

BANNER

# Network interfaces
NICS=$(ip -br addr show 2>/dev/null | grep -E -v '^(lo|flannel|cni|veth|docker|br-)' | head -3)
if [ -n "$NICS" ]; then
    echo "${C}  Network:${R}" >> /etc/issue
    echo "${G}$NICS${R}" >> /etc/issue
    echo "" >> /etc/issue
fi

# Login prompt
echo "${W}  Login: ${O}macula${W} / ${O}macula${R}" >> /etc/issue
echo "" >> /etc/issue
