#!/bin/bash
set -e

source $(dirname $0)/version
source $(dirname $0)/images

cd $(dirname $0)/..

DIST=$(pwd)/dist/artifacts

pushd images/output
build_all "$@"
mkdir -p ${DIST}
copy_all ${DIST} "$@"
popd

mkdir -p ./build
ID=$(docker create ${REPO}/macula-package:${TAG})
docker cp ${ID}:/output/maculaos ./build/
docker rm -fv $ID

docker build \
  --build-arg ARCH=${ARCH} \
  --build-arg REPO=${REPO} \
  --build-arg TAG=${TAG} \
  --build-arg VERSION=${VERSION} \
  --file package/Dockerfile \
  --tag ${REPO}/maculaos:${TAG} \
  --tag ${REPO}/maculaos:latest \
.
docker image save --output ./dist/images.tar \
  ${REPO}/maculaos:${TAG} \
  ${REPO}/maculaos:latest
echo ${REPO}/maculaos:${TAG} > ./dist/images.txt
echo Built ${REPO}/maculaos:${TAG}
